
language: python
sudo: required

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

addons:
  chrome: stable
  firefox: "45.4.0esr"
  apt:
    packages:
      - chromium-chromedriver
      
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver


# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install dash[testing]
  
before_script:
  # include ChromeDriver in PATH
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  # start Chrome and listen on localhost
  - python autoapp.py &  

script: pytest server/src/dashboard/tests --webdriver Firefox  
after_script: pkill -9 -f "autoapp.py"




