
language: python

addons:
  chrome: stable
      
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install dash[testing]
  
# command to run tests
before_script: 
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  -  python autoapp.py &
after_script: pkill -9 -f "autoapp.py"
script: pytest server/src/dashboard/tests 



