
language: python
sudo: required

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

addons:
  firefox: "49.0.2"
  
  
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver


# command to install dependencies
install:
  - npm install selenium-webdriver@^3.0.0
  - pip install -r requirements.txt
  - pip install dash[testing]
  
before_script:
  # start Chrome and listen on localhost
  - python autoapp.py &  

script: pytest server/src/dashboard/tests --webdriver Firefox  
after_script: pkill -9 -f "autoapp.py"




