
language: python

addons:
  chrome: stable
      
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python autoapp.py
  - pytest server/src/dashboard/tests
