dist: trusty
language: python
sudo: true

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

before_script:
  # include ChromeDriver in PATH
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  # start Chrome and listen on localhost
#   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - python autoapp.py & 
  
  

# dist: xenial



python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"


before_install:
  - sudo apt-get update
  - sudo apt-get install -y curl jq
  - sudo chmod +x installation/chromedriver.sh
  - sudo installation/chromedriver.sh latest


# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install dash[testing]



after_script: pkill -9 -f "autoapp.py"

script: pytest server/src/dashboard/tests 




