language: python
sudo: true

python:
  - "3.6"
  - "3.7"
#  - "3.8"

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

install:
  - pip install -r requirements.txt
  - pip install dash[testing]

before_script:
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - ls ${HOME}/bin/
  - flask run

script: pytest server/src/dashboard/tests --headless

after_script: pkill -9 -f "autoapp.py"






