
language: python
sudo: required

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

before_script:
  # include ChromeDriver in PATH
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  # start Chrome and listen on localhost
  - python autoapp.py &  

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install dash[testing]
  



 
after_script: pkill -9 -f "autoapp.py"
script: pytest server/src/dashboard/tests --webdriver Firefox 



