language: python
sudo: true

python:
  - "3.6"
  - "3.7"
#  - "3.8"

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

install:
  - pip install -r requirements.txt
  - pip install dash[testing]
  - pip install flake8

before_script:
  - bundle exec chromedriver-update 83.0.4103.39
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - ls ${HOME}/bin/
  - flask run & # Run in background, to run pytest next

script:
  - flake8 --max-line-length 100
  - pytest server/src/dashboard/tests --headless

#after_script: pkill -9 -f "autoapp.py"






